# Generated by Django 5.1.15 on 2026-10-05 15:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('children', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dose_number', models.PositiveIntegerField(default=1)),
                ('dose_label', models.CharField(max_length=100)),
                ('offset_days', models.IntegerField(default=0)),
                ('offset_months', models.IntegerField(default=0)),
                ('min_interval_days', models.IntegerField(default=28)),
                ('mandatory', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['offset_months', 'offset_days', 'dose_number'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_name', models.CharField(max_length=100)),
                ('official_source', models.CharField(default='Universal Immunization Programme (UIP), MoHFW, Govt of India', max_length=255)),
                ('effective_date', models.DateField()),
                ('is_current', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('target_disease', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('target_child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='children.child')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledDose',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('SCHEDULED', 'Upcoming / Scheduled'), ('DUE_TODAY', 'Due Today'), ('OVERDUE', 'Overdue'), ('COMPLETED', 'Completed'), ('PENDING_VERIFICATION', 'Pending Verification')], default='SCHEDULED', max_length=25)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_doses', to='children.child')),
                ('recommended_dose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_scheduled_doses', to='vaccination.recommendeddose')),
            ],
            options={
                'ordering': ['due_date'],
                'unique_together': {('child', 'recommended_dose')},
            },
        ),
        migrations.AddField(
            model_name='recommendeddose',
            name='schedule_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_doses', to='vaccination.scheduleversion'),
        ),
        migrations.AddField(
            model_name='recommendeddose',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommended_doses', to='vaccination.vaccine'),
        ),
        migrations.CreateModel(
            name='VaccineAdministrationRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('administered_date', models.DateField()),
                ('batch_number', models.CharField(max_length=50)),
                ('clinical_notes', models.TextField(blank=True)),
                ('adverse_reaction', models.BooleanField(default=False)),
                ('adverse_reaction_notes', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('administered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administered_vaccines', to=settings.AUTH_USER_MODEL)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrations', to='children.child')),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='administered_records', to='accounts.clinic')),
                ('scheduled_dose', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='administration_record', to='vaccination.scheduleddose')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='recommendeddose',
            unique_together={('schedule_version', 'vaccine', 'dose_number')},
        ),
    ]
