# Generated by Django 5.1.15 on 2026-10-05 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLModelMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=50)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('accuracy', models.FloatField()),
                ('precision', models.FloatField()),
                ('recall', models.FloatField()),
                ('f1_score', models.FloatField()),
                ('features_used', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChildRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('LOW', 'Low Risk'), ('MEDIUM', 'Moderate Risk'), ('HIGH', 'High Defaulter Risk'), ('INSUFFICIENT_DATA', 'Insufficient Data')], default='INSUFFICIENT_DATA', max_length=30)),
                ('probability', models.FloatField(default=0.0)),
                ('top_risk_factor', models.CharField(default='Standard Monitoring', max_length=255)),
                ('assessed_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessment', to='children.child')),
                ('model_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.mlmodelmetadata')),
            ],
        ),
    ]
