# Generated by Django 5.1.15 on 2026-10-05 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vaccination', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('EMAIL', 'Email'), ('IN_APP', 'In-App Dashboard'), ('SMS', 'SMS (Dev Adapter)')], default='IN_APP', max_length=20)),
                ('scheduled_for', models.DateField()),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_notifications', to=settings.AUTH_USER_MODEL)),
                ('scheduled_dose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='vaccination.scheduleddose')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('scheduled_dose', 'channel', 'scheduled_for')},
            },
        ),
    ]
